### PR TITLE
Atheriel remove connection close workaround

### PR DESCRIPTION
**Pull request by schloerke**
Fixes: #318

Added commit commenting on tcp test path originally created when bug was found.

### CODE REVIEW

**Comment by atheriel** [comment]
I notice that the rebase removed me as the author of the patch, which is a bit disappointing. Was that on purpose?

**Comment by schloerke** [comment]
Hi @atheriel .  

I am SO sorry about that.  100% my fault. I was trying to keep all of the changes made regarding the TCP connections under one PR merge.  I thought squash and merge would credit all authors in the PR.  It didn't.  

I'd be happy to merge the branch in without a squash.  It'd show up as work done in parallel (have 0 effective code change), but you'd be a direct author in the commit history.  I don't feel I can't force push on master given plumber's traction.

**Comment by schloerke** [comment]
@atheriel I just found https://help.github.com/articles/creating-a-commit-with-multiple-authors/ and will be using the feature in the future.

**Comment by atheriel** [comment]
@schloerke I'd never realized squashing had this behaviour before, either. Seems like a bit of an anti-feature. Glad you understand :)

**Pull request merged**
