### PR TITLE
Body encoding

### LINKED ISSUE #153: Cannot POST in UTF-8 under windows
Hello,

I would like to use plumber for credit scoring in our platform. It works fine and it's supereasy. The only problem I've got is that the whole plateform is with UTF-8 encoding and special character are not passed properly.
I guess it's because I run plumber on a windows computer.

Here is an example of what's happening:

File D:/5-Testing/Plumber/test_accent_API.R:

#* @post /text

test_accent_API <- function(Json){
  save(Json,"D:/temp/Json.Rdata")
  return(c(Json$text,"Cécile"))
}

require(plumber)
r <- plumb("D:/5-Testing/Plumber/test_accent_API.R")

r$run(port=443)

image

If I look at the saved R object, we see that it has not been transmitted correctly

> load("D:/Temp/Json.Rdata")
> Json
$text
[1] "Ã©lise"

What I've tried:
* I tried to change default encoding options in R to UTF-8 but it did not work.
* I also tried in postman to specify the charset but it did not change anything either
image

Is there a way to specify the charset for the exchange?

Kind regards,

Jef

### PR DESCRIPTION
**Pull request by farrjere**
This should fix #153.  I added a test to validate that it does handle encoding issues, also I tested locally on my windows partition that it was broken and isn't now. 

I couldn't see any rules for contributing so please let me know if there is something else I need to do.  I did sign the agreement though.

### CODE REVIEW

**Comment by trestletech** [comment]
Thanks for proposing this change! It looks like the CI build now has some failed tests in light of this change. Do you mind taking a look at those?

**Comment by farrjere** [comment]
I am looking into the failures tonight.  I'll post back once I have them fixed.

**Comment by farrjere** [comment]
I accidentally closed and commented.  The pull request is still valid, I will post once I have the tests taken care of.

**Comment by schloerke** [comment]
Closing as merged in #264

**Pull request closed without merging**
