### PR TITLE
Adding support for HEAD verb

### PR DESCRIPTION
**Pull request by thiyagu-p**

### CODE REVIEW

**Comment by trestletech** [comment]
Thanks for submitting the PR.

I'm interested in the change, but it looks like the CI test failed. I haven't looked into it, but can you either resolve that issue or confirm that it's a false positive?

**Comment by thiyagu-p** [comment]
Hi,

I'm not able to reproduce locally and failure message on CI is not clear.

testthat results
================================================================

OK: 225 SKIPPED: 0 FAILED: 0

Error: is.expectation(exp) is not TRUE

Execution halted


Thanks,

Thiyagu

**Comment by trestletech** [comment]
Retriggering the build in Travis now.

**Comment by trestletech** [comment]
Sorry it took so long to get back to this. Build is now passing and this looks good. Thanks for contributing!

**Pull request merged**
