### PR TITLE
Add support for JSON

### PR DESCRIPTION
**Pull request by FvD**
This is an improved version of pull request #51 based on your comments. I took the liberty to update the version number of the package to 0.3.1.

### CODE REVIEW

**Comment by trestletech** [comment]
Looks great! Thanks for contributing! 🍻

**Comment by xiaoyangfeng** [comment]
Looks like what I'm looking for

**Comment by FvD** [comment]
Anything I can do to help you update on CRAN?

**Comment by xiaoyangfeng** [comment]
Hi,

Could you let me now what is the differences between plumber
and session$sendCustomMessage().
Can I receive JSON in AngularJS through plumber?

Best Regards,

Xiaoyang Feng
Cell Phone: 515-240-2495
Email: fengx@uni.edu

**Comment by trestletech** [comment]
Opened #58 to track CRAN work

**Comment by arbab4196** [comment]
Hi,
is possible to have input as a vector for a fuction after converting in api through plumber on swagger UI

**Pull request merged**
