### PR TITLE
Find function when only name is provided

### PR DESCRIPTION
**Pull request by schloerke**
Use the evaluated function not the raw expression.

# Testing Notes

```r
remotes::install_github("trestletech/plumber#416")
p <- callr::r_bg(
  function(){ 
tmp <- tempfile(fileext = ".R")
cat(file = tmp, '
api_msg <- function(msg = "") {
  list(msg = paste0("The message is: \\"", msg, "\\""))
}

# API ----
#* @apiTitle Simple Plumber API

#* Echo back the input
#* @param msg The message to echo
#* @get /echo
api_msg
')

plumber::plumb(tmp)$run(port = 1234)
  }
)

Sys.sleep(1)
x <- httr::GET("127.0.0.1:1234/echo?msg=asdf")
print(httr::content(x))
#> $msg
#> $msg[[1]]
#> [1] "The message is: \"asdf\""
p$kill()
```

### CODE REVIEW

**Comment by schloerke** [comment]
cc @blairj09

**Comment by blairj09** [comment]
This works on my end! One thing I noticed given the following example:
```r
# Setup ----
library(plumber)

source("utils.R")
api_msg <- function(msg = "") {
  list(msg = paste0("The message is: '", msg, "'"))
}

# API ----
#* @apiTitle Simple Plumber API

#* Echo back the input
#* @param msg The message to echo
#* @get /utils_echo
utils_msg

#* Echo back the input
#* @param msg The message to echo
#* @get /api_echo
api_msg
```

Where `utils_msg` is defined in `utils.R`. Both endpoints work as expected. However, when I terminate the Plumber API process after running it, `utils_msg` is persisted in my global environment while `api_msg` is not. Is this expected?

**Comment by schloerke** [comment]
@blairj09 Try adding `local = TRUE` to the source call.

```r
source("utils.R", local = TRUE)
```

**Comment by blairj09** [comment]
Ahh that works! This all looks good to me 😄

**Pull request merged**
